### PR TITLE
chore: Update dependencies

### LINKED ISSUE #468: Drop Node 8 support
Because it's [EOL](https://nodejs.org/en/about/releases).

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Closes #468 

BREAKING CHANGE: Node >=10 is required

### CODE REVIEW

**Comment by ai** [comment]
I closed this PR because of the reason discussed in issue.

**Comment by MichaelDeBoey** [comment]
@ai Will resubmit without breaking change

**Comment by ai** [comment]
We need a discussion before any pull request

**Comment by MichaelDeBoey** [comment]
This isn't breaking anything tho

**Pull request closed without merging**
