### PR TITLE
Electron resolves to node+chrome, electron-releases

### PR DESCRIPTION
**Pull request by mutech**
Electron queries resolve to both chrome and node versions, replaced electron-2-chromium with electron-releases, major and minor versions resolve to oldest concrete version (3 -> 3.0.0, 1.1 -> 1.1.0).

Uses electron-releases as devDependency and generates e2cn.js via `npm run importdata` to reducce the package size penalty.

This still breaks the size limit of 9K (10.7K), but that seems to be an acceptable margin.

I don't like the solution using a script to extract the data from electron-releases, but I also don't have a good idea how to do it otherwise.

### CODE REVIEW

**Comment by mutech** [comment]
Would fix #328 and #329

**Comment by mutech** [comment]
Size is down to 9.8K with the latest commit, but that's about what can be done.

The remaining problem is that the script has to be run to update the packed file whenever the dependency to electron-releases is updated.

**Comment by ai** [comment]
> Uses electron-releases as devDependency and generates e2cn.js via npm run importdata to reducce the package size penalty.

Sorry, I can't manually call `yarn importdata` on every Electron release. It will require a lot of work and I will not able to do it every day.

**Comment by ai** [comment]
There is another way. We can write to Electron developers and soonest to add this “lite” data to their npm package.

**Comment by ai** [comment]
I am closing this PR since manually updates is not a option

**Pull request closed without merging**
