### PR TITLE
Retain String.prototype.substring (ex. substr)

### PR DESCRIPTION
**Pull request by mcdmaster**
Please accept this. In terms of the issue #527, I think that we can keep ourselves hanging on the Old-Skool style `String.prototype.substring()` so that we can lessen the compatibility risks. Thank you for understanding.

### CODE REVIEW

**Comment by ai** [comment]
Hi. Thanks for PR, but tests are broken right now.

**Comment by mcdmaster** [comment]
@ai I knew. The symptom that I am facing with an error message `"Unknown browser query ``. Maybe you are using old Browserslist or made typo in query"` is what I encountered several times before the PR. I will much appreciate if you have any way to overcome this situation. Thank you anyway.

**Comment by ai** [comment]
Sorry. I am OK with the current code. Changes will took a time from my other open source projects and could lead to regressions and more time spendings.

It is your invitative. You should give me a proof that your suggestion is safe.

Do you want to close PR since changes have unpredictable breaking changes?

**Comment by mcdmaster** [comment]
Thank you for getting back to me. Can you please give me some time for investigating how to get rid of the error? Although I do suppose that the very error has been residual as my change did not raise it, I am much interested to resolve the evil one for smooth development activities thereafter. Anyway, I do not intend to close this until I can find a resolution for not only the issue itself that I raised but also the "residual" error that can be easily found whenever I googled the error message.

**Comment by ai** [comment]
Sorry. This PR looks too dangerous for just code style improvments.

**Comment by mcdmaster** [comment]
Noted. Thanks

**Pull request closed without merging**
