### PR TITLE
Add --ignore-workspace-root-check to yarn commands in update-db

### PR DESCRIPTION
**Pull request by fnune**
https://github.com/browserslist/browserslist/issues/552

Otherwise update-db.js doesn't work in yarn workspaces.

### CODE REVIEW

**Comment by ai** [comment]
Can you also add a test to avoid regression in the future?

**Comment by fnune** [comment]
I put out this one quickly because it was a two-liner, I'll have some time to add a test later in the week I guess.

**Comment by ai** [comment]
Just create a small monorepo project in `test/fixtures/monorepo` (just a few `package.json` and single `yarn.lock`) and add copy [this test](https://github.com/browserslist/browserslist/blob/master/test/update-db.test.js#L96) for the dir

**Comment by ivanoats** [comment]
nice work, I appreciate this because our project uses workspaces, too.

**Comment by ai** [comment]
I will release it tomorrow. Thanks

**Comment by ai** [comment]
Released in 4.14.7

**Pull request merged**
