### PR TITLE
fix: browserslist --update-db for yarn v2+ lockfile

### LINKED ISSUE #577: --update-db fails with Yarn v2 lock file
## Description
When using Yarn v2, running `npx browserslist@latest --update-db` fails with the error `Cannot read property '1' of null`.  Calling `yarn run browserslist --update-db` gives the error with some more details:

```
C:\inetpub\wwwroot\blt\.yarn\cache\browserslist-npm-4.16.1-37866cfd90-56f51464c3.zip\node_modules\browserslist\update-db.js:57
    if (match[1]) return match[1]
             ^

TypeError: Cannot read property '1' of null
    at getCurrentVersion (C:\inetpub\wwwroot\blt\.yarn\cache\browserslist-npm-4.16.1-37866cfd90-56f51464c3.zip\node_modules\browserslist\update-db.js:57:14)
    at updateDB (C:\inetpub\wwwroot\blt\.yarn\cache\browserslist-npm-4.16.1-37866cfd90-56f51464c3.zip\node_modules\browserslist\update-db.js:179:17)
    at Object.<anonymous> (C:\inetpub\wwwroot\blt\.yarn\cache\browserslist-npm-4.16.1-37866cfd90-56f51464c3.zip\node_modules\browserslist\cli.js:40:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.external_module_.Module._load (C:\inetpub\wwwroot\blt\.pnp.js:4980:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

<details>
<summary>
<code>package.json</code>
</summary>
```json
{
  "name": "blt",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "browserslist": "^4.16.1"
  }
}
```
</details>
<details>
<summary>
<code>yarn.lock</code>
</summary>
```yaml
# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 4
  cacheKey: 7

"blt@workspace:.":
  version: 0.0.0-use.local
  resolution: "blt@workspace:."
  dependencies:
    browserslist: ^4.16.1
  languageName: unknown
  linkType: soft

"browserslist@npm:^4.16.1":
  version: 4.16.1
  resolution: "browserslist@npm:4.16.1"
  dependencies:
    caniuse-lite: ^1.0.30001173
    colorette: ^1.2.1
    electron-to-chromium: ^1.3.634
    escalade: ^3.1.1
    node-releases: ^1.1.69
  bin:
    browserslist: cli.js
  checksum: 56f51464c3a3bd9b2aeb75ded1dc3fce5ad91bd6d84187aba812a78ba66b69bc97c2de25a1b7409daac3c0049e979bf0faa6cca4aacce0abcaf3107c250ce3fb
  languageName: node
  linkType: hard

"caniuse-lite@npm:^1.0.30001173":
  version: 1.0.30001177
  resolution: "caniuse-lite@npm:1.0.30001177"
  checksum: a43eafb57339093bf3343bc6f57cc21ff6779af44c9a26cc078c3b335db12598179d1333a1cbdd6fd25a2c08cfc550c78538b48fbb3e9c383f46460a1c32a1c0
  languageName: node
  linkType: hard

"colorette@npm:^1.2.1":
  version: 1.2.1
  resolution: "colorette@npm:1.2.1"
  checksum: 1cc21ad4b84777a424794f78b6bb6a44b614ae17dcea91762199339f8047598e6d981249eeef7ea588c99eaf062be8fcdcd4866c112998922ed854db6dde96f9
  languageName: node
  linkType: hard

"electron-to-chromium@npm:^1.3.634":
  version: 1.3.639
  resolution: "electron-to-chromium@npm:1.3.639"
  checksum: bf8b79e55d50ddcd55b029feb161a56250f3a8980b5c11b47055fd983b9306ad8c69c0501eef9317e0e03f8c5d69fecb97338c08df8c9456953f5741646794c1
  languageName: node
  linkType: hard

"escalade@npm:^3.1.1":
  version: 3.1.1
  resolution: "escalade@npm:3.1.1"
  checksum: 1e31ff50d66f47cd0dfffa702061127116ccf9886d1f54a802a7b3bc95b94cab0cbf5b145cc5ac199036df6fd9d1bb24af1fa1bfed87c94879e950fbee5f86d1
  languageName: node
  linkType: hard

"node-releases@npm:^1.1.69":
  version: 1.1.69
  resolution: "node-releases@npm:1.1.69"
  checksum: 240b2534f32c8bbdfefb1fb052d2b1c198f3a745141ce245c6c5241a6efefae22d356b66965e5250869013c3c4777050cdca78d39f3b46965166b5f3e02b08d7
  languageName: node
  linkType: hard
```
</details>

Here's a zip of the whole project (just `package.json` and various Yarn artifacts): [sscce.zip](https://github.com/browserslist/browserslist/files/5816478/sscce.zip)

### LINKED ISSUE #616: If caniuse-lite isn't in package.json directly, `yarn info` fails
If `caniuse-lite` is included as as transitive dependency of some other package like NextJS, I'm finding that when I run `npx browserslist@latest --update-db` then it fails with this error:

```
Command failed: yarn info caniuse-lite --json
```

I use Yarn 3.0.1. When I add `caniuse-lite` directly, then instead of that error, I get:

```
Cannot read property 'version' of undefined
```

For reference, `yarn info caniuse-lite --json` returns:

```
{"value":"caniuse-lite@npm:1.0.30001252","children":{"Version":"1.0.30001252"}}
```

And if this were to work without `caniuse-lite` being installed as a direct dependency, the `yarn info` command just needs the `--recursive` flag:

```
yarn info caniuse-lite --recursive --json
```

Yielding the same result as above.

It seems that the `update-db` command doesn't work properly for Yarn Berry. I presume that even if I got past this, it would fail later due to #577 because it doesn't use `yarn up -R caniuse-lite` as suggested there.

### PR DESCRIPTION
**Pull request by himankpathak**
### Description
Fix `browserslist --update-db` for yarn v2+ lockfiles

### Verification Process
- Tested on local
- update-db test case passes

### Issue
Closes #577, closes #616

### CODE REVIEW

**Comment by himankpathak** [comment]
Updated update-db tests:
```
 PASS  test/update-db.test.js (68.396s)
--------------|---------|----------|---------|---------|-------------------
File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
--------------|---------|----------|---------|---------|-------------------
All files     |     100 |    98.64 |     100 |     100 |
 browser.js   |     100 |      100 |     100 |     100 |
 error.js     |     100 |      100 |     100 |     100 |
 index.js     |     100 |    98.98 |     100 |     100 | 159,458,579
 node.js      |     100 |    99.31 |     100 |     100 | 105
 update-db.js |     100 |    95.83 |     100 |     100 | 97-98,159
--------------|---------|----------|---------|---------|-------------------

Test Suites: 34 passed, 34 total
Tests:       282 passed, 282 total
Snapshots:   0 total
Time:        68.744s
Ran all test suites.
```

**Comment by ai** [comment]
It is OK to avoid calling Yarn 2 tests on old Node.js versions

**Comment by ai** [comment]
> Updated update-db tests

Looks good. But we need to fix CI for all Node.js versions.

It is OK to avoid calling Yarn 2 tests on old Node.js versions

**Comment by ai** [comment]
When I try to run `yarn test` locally I get:

```
 FAIL  test/update-db.test.js (30.302s)
  ● updates caniuse-lite for yarn v2

    Command failed: yarn info caniuse-lite --json

      51 |     if (lock.version === 1) {
      52 |       return JSON.parse(
    > 53 |         childProcess.execSync('yarn info caniuse-lite --json').toString()
         |                      ^
      54 |       ).data
      55 |     } else {
      56 |       return JSON.parse(

      at getLatestInfo (update-db.js:53:22)
      at updateDB (update-db.js:263:16)
      at runUpdate (test/update-db.test.js:36:3)
      at Object.<anonymous> (test/update-db.test.js:219:1
```

Here is an error text of calling `yarn info caniuse-lite --json` in `test/fixtures/update-yarn-v2`

```
Usage Error: No package matched your request

$ yarn info [-A,--all] [-R,--recursive] [-X,--extra #0] [--cache] [--dependents] [--manifest] [--name-only] [--virtuals] [--json] ...
```

Yarn version: 3.0.2 (or 1.22.10 outside of Yarn 2 fixture).

How I can fix it?

**Comment by ai** [comment]
The same problem on CI: https://github.com/browserslist/browserslist/actions/runs/1201023019

**Comment by himankpathak** [comment]
@ai , 
`yarn info caniuse-lite --json` is the command for Yarn v1.
`yarn npm info caniuse-lite --json` is the command for Yarn v2+.

How is the program entering `lock.version === 1` if statement?
Could it be lock file version is not matching the `yarn --version` you are using?

**Comment by himankpathak** [comment]
Hey @ai , 
This looks like it was caused due to git conflict resolution.
Statement `lock = detectLockfileVersion(lock)` and `detectLockfileVersion()` function is missing on `main` branch.

**Comment by himankpathak** [comment]
@ai , 
Found it. this is causing the issue.
`lock.version = lock.content.search(/# yarn lockfile v1/g) ? 1 : 2`

It should be something like this:
`lock.version = ( lock.content.search(/# yarn lockfile v1/g) !== -1 ) ? 1 : 2`

**Comment by ai** [comment]
Oops. Sorry,it was my fault.

Will fix it and release today

**Comment by ai** [comment]
Thanks. Released in 4.17.

**Pull request merged**
