### PR TITLE
Fix ReDoS

### PR DESCRIPTION
**Pull request by yetingli**
Fix 6 ReDoS-vulnerable regexes with pattern `\d*\.?\d+`.
Fix strategy: Replace  `\d*\.?\d+` with  `d+|\d*\.\d+`

### CODE REVIEW

**Comment by ai** [comment]
Thanks for finding ReDoS in PostCSS and Browserslist.

Seems like this RegExp change breaks the query scanner. I will try to fix it.

**Comment by ai** [comment]
I fixed RegExp by 1013a18

**Comment by yetingli** [comment]
> I fixed RegExp by [1013a18](https://github.com/browserslist/browserslist/commit/1013a1847931a209c34a704aebc85a8c091286e7)

The fixed regex is also safe.

**Comment by ai** [comment]
Do you have a Twitter account to mention you in release tweets?

**Comment by ai** [comment]
The fix was released in 4.16.5.

**Comment by yetingli** [comment]
Thanks a lot! My Twitter account is yetingli26

**Pull request merged**
