### PR TITLE
Work in progress: Implementation of "project browserslist" and "proje…

### PR DESCRIPTION
**Pull request by mutech**
This is a preliminary implementation attempt for #327

It seems to work fine for simple cases, I implemented `project browserslist` and `project electron version`. `project node version(s)` requires more work, because there you're likely to use more complex version specs.

This is not ready to be merged, send the PR just for you to take a look at it and see if it's worth spending more time to get it right.

### CODE REVIEW

**Comment by ai** [comment]
What is `project browserslist`?

We discussed `project node` and `project electron`.

**Comment by mutech** [comment]
> What is `project browserslist`?
>
> We discussed `project node` and `project electron`.

I described it together with these two. You can f.e. specify in a .browsersrc somewhere:
```
project browserslists, somequery > 5, project electron version
```
And what's supposed to happen is that the package.json browserslist is inserted in place of 'project browserslist'.

It was easy to implement (once the package loading functionality was there) and it's easy to remove, just wanted to show you what I mean.

`project node versions` is coming, but that's a bit trickier because of the version parsing necessary to get it right.

**Comment by mutech** [comment]
> Also, I prefer to avoid unnecessary code or of browser build. So, let's keep maximum code in `./node.js`.

I don't really understand what you mean.

**Comment by mutech** [comment]
Did as you said. `project browserslist` is removed, all code that can be moved from index.js is in node.js.

I don't want to provoke an unnecessary discussion, but how does browserslist run in the browser? Do they plug in a replacement for the functionality in node.js?

Anyway, this is where you have to take over and merge or close the PR.

**Comment by ai** [comment]
> how does browserslist run in the browser?

Some users put Autoprefixer in a browser. There are good cases (like websites for developers http://autoprefixer.github.io/ru/ or https://browserl.ist/ ). There are bad cases (add client-side Autoprefixer for CSS-in-JS with browser runtime).

As result, it is not #1 priority, but we should think about it.

**Comment by ai** [comment]
PR now is perfect 👍 Great work.

I will not able to release it only on next week 😓. Do you want to add `project node` to this PR?

**Comment by ai** [comment]
@mutech I can merge and release it when you will add `project node`

**Comment by mutech** [comment]
@ai At the weekend, quite busy now

**Comment by ai** [comment]
I am closing since it looks dead.

Feel free to ask me to re-open it if you want to continue.

**Comment by alecmev** [comment]
@ai Would you accept a revived PR for `project electron`, without `project node`?

**Comment by ai** [comment]
Right now I do not have enough time for open source. If it is not critical, let's do it later

**Comment by alecmev** [comment]
As it happens, I don't have time for it right now either, just asking ahead :slightly_smiling_face: When will your open source availability improve?

**Comment by ai** [comment]
I am not sure. I lost motivation of supporting this project after big companies and front-end opinion leaders ignored [our funding](https://opencollective.com/browserslist).

**Comment by ai** [comment]
@alecmev I am working in Evil Martians and they give me resources (like a logo) and close eyes when I use working hours. It is enough to support Browserslist, but not enough to do a big refactoring, which we need for the project to avoid security problems like [“ESLint Malicious Package”](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes).

**Pull request closed without merging**
