### PR TITLE
Allow "@scope/browserslist-config/somefile"

### PR DESCRIPTION
**Pull request by Schweinepriester**
See #284.

### CODE REVIEW

**Comment by ai** [comment]
Thanks. Right now I am on Def Con. I will review it on next week.

**Comment by ai** [comment]
With this regexp you can pass something `extends @good/browserslist-config/../evil/hack.js`.

Can you make regexp more strict?

**Comment by ai** [comment]
Nope, it is not secure too. Attacker can just write `extends @good/browserslist-config/subdir/../../evil/hack.js` 😉

We need to find `/./` and `/../` in any part. Maybe we should use two RegExp.

**Comment by Schweinepriester** [comment]
Sorry for the late response, but doesn't https://github.com/browserslist/browserslist/blob/master/node.js#L24-L27
```js
if (name.indexOf('.') !== -1) {
  throw new BrowserslistError(
    '`.` not allowed in Browserslist config name. ' + use)
}
```
already cover this, by generally disallowing any `.` in the config name, thus also rejecting `/./` as well as `/../`?

If so, I believe the current changes in the pull request would suffice.

If not, I experimented with https://regex101.com/r/N4SzUq/1 as second RegExp.

**Comment by ai** [comment]
Right, I forgot about `checkExtend`

**Comment by ai** [comment]
Released in 4.3

**Pull request merged**
